name: update-and-publish
on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install Dependencies
        run: |
          pip install -r ./requirements.txt
      - name: Download
        run: |
          instaloader pylon_ceramics --no-videos --fast-update --no-profile-pic  --dirname-pattern=instagram
        env:
          PYTHONUNBUFFERED: 1
      - name: Update Instagram data
        run: |
          ./scripts/update-instagram.py ${{ secrets.RAPIDAPI_KEY }}

      - name: Update markdown content
        run: |
          python3 ./scripts/update-content.py
        
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          add: 'instagram src/instagram-data.json'
          author_name: 'Pylon Ceramics'
          author_email: 'marekventur+pylon-ceramics-instagram@gmail.com'
          message: 'Update'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: build